import argparse
from pathlib import Path

import numpy as np


INPUT_SIZE = 28 * 28
CLASS_COUNT = 10


def format_float(value: float) -> str:
    return f"{value:.8e}f"


def write_header(path: Path) -> None:
    path.write_text(
        """#ifndef PERCEPTRON_DATA_H
#define PERCEPTRON_DATA_H

#include <stdint.h>

#define PERCEPTRON_INPUT_SIZE 784U
#define PERCEPTRON_CLASS_COUNT 10U

#define PERCEPTRON_MODEL_GENERATED 1

extern const float g_perceptron_weights[PERCEPTRON_CLASS_COUNT][PERCEPTRON_INPUT_SIZE];
extern const float g_perceptron_bias[PERCEPTRON_CLASS_COUNT];

#endif /* PERCEPTRON_DATA_H */
""",
        encoding="utf-8",
    )


def write_source(path: Path, weights: np.ndarray, bias: np.ndarray) -> None:
    with path.open("w", encoding="utf-8") as f:
        f.write('#include "PerceptronData.h"\n\n')
        f.write("const float g_perceptron_weights[PERCEPTRON_CLASS_COUNT][PERCEPTRON_INPUT_SIZE] = {\n")
        for class_idx in range(CLASS_COUNT):
            f.write("    {\n")
            row = weights[class_idx]
            for offset in range(0, INPUT_SIZE, 8):
                values = ", ".join(format_float(v) for v in row[offset : offset + 8])
                f.write(f"        {values},\n")
            f.write("    },\n")
        f.write("};\n\n")
        f.write("const float g_perceptron_bias[PERCEPTRON_CLASS_COUNT] = {\n    ")
        f.write(", ".join(format_float(v) for v in bias))
        f.write("\n};\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Export MNIST perceptron weights to C arrays.")
    parser.add_argument("weights", help=".npz file generated by train_perceptron.py")
    parser.add_argument("--out-dir", default=None, help="Directory for PerceptronData.c/h")
    args = parser.parse_args()

    data = np.load(args.weights)
    weights = data["weights"].astype(np.float32)
    bias = data["bias"].astype(np.float32)

    if weights.shape != (CLASS_COUNT, INPUT_SIZE):
        raise ValueError(f"expected weights shape {(CLASS_COUNT, INPUT_SIZE)}, got {weights.shape}")
    if bias.shape != (CLASS_COUNT,):
        raise ValueError(f"expected bias shape {(CLASS_COUNT,)}, got {bias.shape}")

    repo_root = Path(__file__).resolve().parents[2]
    out_dir = Path(args.out_dir).resolve() if args.out_dir else repo_root / "User" / "model"
    out_dir.mkdir(parents=True, exist_ok=True)
    write_header(out_dir / "PerceptronData.h")
    write_source(out_dir / "PerceptronData.c", weights, bias)
    print(f"exported {out_dir / 'PerceptronData.c'}")
    print(f"exported {out_dir / 'PerceptronData.h'}")


if __name__ == "__main__":
    main()
