from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np


INPUT_SIZE = 28 * 28
CLASS_COUNT = 10


def scalar_str(data: dict[str, np.ndarray], key: str) -> str:
    return str(data[key].tolist())


def scalar_int(data: dict[str, np.ndarray], key: str) -> int:
    return int(data[key].tolist())


def format_float(value: float) -> str:
    return f"{float(value):.8e}f"


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_matrix(f, name: str, rows: int, cols: int, values: np.ndarray) -> None:
    f.write(f"const float {name}[{rows}][{cols}] = {{\n")
    for row in range(rows):
        f.write("    {\n")
        for offset in range(0, cols, 8):
            line = ", ".join(format_float(v) for v in values[row, offset : offset + 8])
            f.write(f"        {line},\n")
        f.write("    },\n")
    f.write("};\n\n")


def write_vector(f, name: str, size: int, values: np.ndarray) -> None:
    f.write(f"const float {name}[{size}] = {{\n    ")
    f.write(", ".join(format_float(v) for v in values))
    f.write("\n};\n\n")


def write_header(path: Path, model_type: str, model_name: str, hidden_size: int) -> None:
    model_type_macro = "MODEL_TYPE_MLP" if model_type == "mlp" else "MODEL_TYPE_PERCEPTRON"
    path.write_text(
        f"""#ifndef MODEL_DATA_H
#define MODEL_DATA_H

#include <stdint.h>

#define MODEL_TYPE_PERCEPTRON 1
#define MODEL_TYPE_MLP 2

#define MODEL_INPUT_SIZE 784U
#define MODEL_CLASS_COUNT 10U
#define MODEL_HIDDEN_SIZE {hidden_size}U
#define MODEL_TYPE {model_type_macro}
#define MODEL_NAME {c_string(model_name)}
#define MODEL_TYPE_NAME {c_string(model_type)}
#define MODEL_GENERATED 1

#if MODEL_TYPE == MODEL_TYPE_MLP
extern const float g_model_hidden_weights[MODEL_HIDDEN_SIZE][MODEL_INPUT_SIZE];
extern const float g_model_hidden_bias[MODEL_HIDDEN_SIZE];
extern const float g_model_output_weights[MODEL_CLASS_COUNT][MODEL_HIDDEN_SIZE];
#else
extern const float g_model_output_weights[MODEL_CLASS_COUNT][MODEL_INPUT_SIZE];
#endif
extern const float g_model_output_bias[MODEL_CLASS_COUNT];

#endif /* MODEL_DATA_H */
""",
        encoding="utf-8",
    )


def write_source(path: Path, data: dict[str, np.ndarray], model_type: str, hidden_size: int) -> None:
    output_weights = data["output_weights"].astype(np.float32)
    output_bias = data["output_bias"].astype(np.float32)

    with path.open("w", encoding="utf-8") as f:
        f.write('#include "ModelData.h"\n\n')

        if model_type == "mlp":
            hidden_weights = data["hidden_weights"].astype(np.float32)
            hidden_bias = data["hidden_bias"].astype(np.float32)
            if hidden_weights.shape != (hidden_size, INPUT_SIZE):
                raise ValueError(f"unexpected hidden weight shape: {hidden_weights.shape}")
            if hidden_bias.shape != (hidden_size,):
                raise ValueError(f"unexpected hidden bias shape: {hidden_bias.shape}")
            if output_weights.shape != (CLASS_COUNT, hidden_size):
                raise ValueError(f"unexpected output weight shape: {output_weights.shape}")
            write_matrix(f, "g_model_hidden_weights", hidden_size, INPUT_SIZE, hidden_weights)
            write_vector(f, "g_model_hidden_bias", hidden_size, hidden_bias)
            write_matrix(f, "g_model_output_weights", CLASS_COUNT, hidden_size, output_weights)
        else:
            if output_weights.shape != (CLASS_COUNT, INPUT_SIZE):
                raise ValueError(f"unexpected output weight shape: {output_weights.shape}")
            write_matrix(f, "g_model_output_weights", CLASS_COUNT, INPUT_SIZE, output_weights)

        if output_bias.shape != (CLASS_COUNT,):
            raise ValueError(f"unexpected output bias shape: {output_bias.shape}")
        write_vector(f, "g_model_output_bias", CLASS_COUNT, output_bias)


def main() -> None:
    parser = argparse.ArgumentParser(description="Export perceptron or MLP model to STM32 C arrays.")
    parser.add_argument("weights", help="model.npz generated by train_model.py")
    parser.add_argument("--out-dir", default=None, help="Directory for ModelData.c/h")
    args = parser.parse_args()

    npz = np.load(args.weights)
    data = {key: npz[key] for key in npz.files}
    if "model_type" not in data:
        if "weights" not in data or "bias" not in data:
            raise ValueError("legacy perceptron export requires weights and bias arrays")
        data = {
            "model_type": np.array("perceptron"),
            "model_name": np.array("perceptron"),
            "input_size": np.int32(INPUT_SIZE),
            "class_count": np.int32(CLASS_COUNT),
            "hidden_size": np.int32(0),
            "output_weights": data["weights"].astype(np.float32),
            "output_bias": data["bias"].astype(np.float32),
        }

    model_type = scalar_str(data, "model_type")
    model_name = scalar_str(data, "model_name")
    hidden_size = scalar_int(data, "hidden_size")

    if scalar_int(data, "input_size") != INPUT_SIZE:
        raise ValueError("model input size is not 784")
    if scalar_int(data, "class_count") != CLASS_COUNT:
        raise ValueError("model class count is not 10")
    if model_type not in {"perceptron", "mlp"}:
        raise ValueError(f"unsupported model type: {model_type}")

    repo_root = Path(__file__).resolve().parents[2]
    out_dir = Path(args.out_dir).resolve() if args.out_dir else repo_root / "User" / "model"
    out_dir.mkdir(parents=True, exist_ok=True)
    write_header(out_dir / "ModelData.h", model_type, model_name, hidden_size)
    write_source(out_dir / "ModelData.c", data, model_type, hidden_size)
    print(f"exported {model_name} ({model_type}) to {out_dir}")


if __name__ == "__main__":
    main()
